language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Qt
  - sudo apt-get update -qq
  - sudo apt-get install -y libqt4-dev qt4-qmake libsmokeqtgui4-3 libsmokeqt4-dev
  # X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # CL
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Newer deps
  - git clone https://github.com/Shinmera/qtools.git ~/quicklisp/local-projects/qtools
  - git clone https://github.com/Shinmera/verbose.git ~/quicklisp/local-projects/verbose
  - git clone https://github.com/Shinmera/simple-tasks.git ~/quicklisp/local-projects/simple-tasks
  - git clone https://github.com/Shinmera/trivial-main-thread.git ~/quicklisp/local-projects/trivial-main-thread

script:
  # Load qtools first to work around :defsystem-depends-on bug.
  - cl -e '(ql:quickload :qtools)'
       -e '(ql:quickload :halftone)'
       -e '(asdf:operate :program-op :halftone :force T)'

notifications:
  email:
    - shinmera@tymoon.eu