language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Qt
  - sudo apt-get update -qq
  - sudo apt-get install -y libqt4-dev qt4-qmake libsmokeqtgui4-3 libsmokeqt4-dev
  # X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Qtools
  - git clone https://github.com/Shinmera/qtools.git ~/quicklisp/local-projects/qtools
  # CL
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -e '(asdf:operate :program-op :halftone :force T)'

notifications:
  email:
    - shinmera@tymoon.eu